# Generated by Django 4.2.16 on 2024-11-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_member_subject1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='subject2',
            field=models.CharField(max_length=30, null=True, verbose_name='주제2'),
        ),
    ]
