# Generated by Django 4.2.16 on 2024-12-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_member_subject2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='subject1',
            field=models.CharField(max_length=1000, null=True, verbose_name='주제1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='subject2',
            field=models.CharField(max_length=1000, null=True, verbose_name='주제2'),
        ),
    ]
